layout_spectrum: 0
typography_spectrum: 0.1466165
color:
  saturation: 0.5000232
  lightness: 0.9594591
  brandStrength: 0.3909914
  rhythmicContrast: 0.8810232
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: amplify healthcare
